services:
  - type: web
    name: c&c-global-pos
    env: python
    buildCommand: bash build.sh
    startCommand: python app.py
    envVars:
      - key: SECRET_KEY
        value: c&c-global-secret-key-8583
      - key: FLASK_ENV
        value: production
